version:
jobs:
  build:

    working_directory: ~/instaclustr-commons

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: instaclustr-commons-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: instaclustr-commons-{{ checksum "pom.xml" }}

      - run: mvn clean install -Dcassandra.version=3.11.11

      - store_test_results:
          path: ~/instaclustr-commons/target/surefire-reports

      - store_artifacts:
          path: ~/instaclustr-commons/target/instaclustr-commons.jar